plugins {
    id 'nva.root-module-conventions'
}

nva {
    dependencyAnalysis {
        enforced = true
    }
    spotless {
        enabled = false
    }
    jacoco {
        // FIXME: Remove dead code and add tests for remaining gaps
        minMethodCoverage = new BigDecimal('0.920')
        minClassCoverage = new BigDecimal('0.920')
    }
}
