plugins {
    id 'nva.orcid.client.java-conventions'
}

dependencies {
    api(nvaCatalog.aws.sdk.dynamo)
    api(nvaCatalog.jackson.annotations)
    api(nvaCatalog.jackson.databind)
    api(nvaLibs.json)
    implementation(nvaCatalog.resilience4j.retry)
    implementation(nvaCatalog.vavr)
    implementation(nvaLibs.core)
    implementation(project(":orcid-constants"))
    runtimeOnly(nvaCatalog.jackson.datatype.jsr310)
    testImplementation(nvaCatalog.aws.java.sdk.core)
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.mockito.core)
    testImplementation(nvaLibs.testutils)
    testImplementation(project(":orcid-testutils"))
    testRuntimeOnly(nvaCatalog.junit.jupiter.engine)
    testRuntimeOnly(nvaCatalog.junit.platform.launcher)
}