plugins {
    id 'nva.orcid.client.java-conventions'
    id 'java-test-fixtures'
}

dependencies {
    api(nvaCatalog.aws.sdk.dynamo)
    api(nvaCatalog.jackson.annotations)
    api(nvaCatalog.jackson.databind)
    api(nvaLibs.json)
    implementation(nvaCatalog.resilience4j.retry)
    implementation(nvaCatalog.vavr)
    implementation(nvaLibs.core)
    runtimeOnly(nvaCatalog.jackson.datatype.jsr310)
    testFixturesApi(nvaCatalog.aws.sdk.dynamo)
    testFixturesApi(nvaCatalog.junit.jupiter.api)
    testFixturesImplementation(nvaCatalog.aws.dynamodb.local)
    testFixturesImplementation(nvaLibs.core)
    testImplementation(nvaCatalog.aws.java.sdk.core)
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.mockito.core)
    testImplementation(nvaLibs.testutils)
    testRuntimeOnly(nvaCatalog.junit.jupiter.engine)
    testRuntimeOnly(nvaCatalog.junit.platform.launcher)
}